import { useState } from "react";
import { Database, LockKeyhole, Save, ShieldCheck } from "lucide-react";
import { useSettings } from "../stores";

export default function ResearchSettings() {
  const settings = useSettings();
  const [apiUrl, setApiUrl] = useState(settings.apiUrl);
  function save() { settings.update({ apiUrl }); }
  return <div className="mx-auto max-w-4xl space-y-5 p-5"><div><h1 className="text-2xl font-black text-white">Settings</h1><p className="mt-1 text-sm text-slate-400">Market-data and research configuration. Execution settings are intentionally unavailable.</p></div><section className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5"><div className="flex items-center gap-2 text-sm font-bold text-emerald-200"><ShieldCheck className="h-5 w-5" />Read-only guarantee</div><p className="mt-2 text-sm leading-6 text-slate-300">The backend provider has no order-placement or position-mutation capability. BUY and SELL are analytical labels only.</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-5"><div className="flex items-center gap-2 text-sm font-bold text-white"><Database className="h-4 w-4 text-indigo-300" />Backend connection</div><label className="mt-4 block text-xs text-slate-400">Backend API proxy URL<input value={apiUrl} onChange={(event) => setApiUrl(event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-white" /></label><button onClick={save} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white"><Save className="h-4 w-4" />Save connection</button></section><section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-5"><div className="flex items-center gap-2 text-sm font-bold text-white"><LockKeyhole className="h-4 w-4 text-amber-300" />Server-side credentials</div><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-400"><li>• FYERS OAuth credentials and access tokens remain on the backend.</li><li>• Crypto public market data requires no exchange key or wallet.</li><li>• No LLM key is currently required; analysis uses the deterministic read-only adapter.</li></ul></section></div>;
}
